name: Java CI - Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
      id-token: write # This is required for the OIDC token

    env:
      MAVEN_ARGS: -V -B --no-transfer-progress

    steps:
      - uses: actions/checkout@v4

      - uses: jfrog/setup-jfrog-cli@v4
        id: jfrog
        env:
          JF_URL: https://develocitytia.jfrog.io
        with:
          oidc-provider-name: github

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
          server-id: artifactory
          server-username: JFROG_USER
          server-password: JFROG_PASSWORD

      - name: Build with Maven
        run: ./mvnw verify
        env:
          JFROG_USER: ${{ steps.jfrog.outputs.oidc-user }}
          JFROG_PASSWORD: ${{ steps.jfrog.outputs.oidc-token }}
          CI_ID: ${{ github.run_id }}
