name: Java CI - Merge & Publish

on:
  push:
    branches: [ "main" ]

jobs:

  token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for the OIDC token

    outputs:
      oidc-user: ${{ steps.jfrog.outputs.oidc-user }}
      oidc-token: ${{ steps.jfrog.outputs.oidc-token }}

    steps:
      - uses: jfrog/setup-jfrog-cli@v4
        id: jfrog
        env:
          JF_URL: https://develocitytia.jfrog.io
        with:
          oidc-provider-name: github

  build:
    runs-on: ubuntu-latest
    needs: token

    env:
      MAVEN_ARGS: -V -B --no-transfer-progress

    services:
      develocity-attestations:
        image: registry.gitlab.com/cloudnative20031/opa/develocity-attestation-generator:main
        env:
          DEVELOCITY_URL: https://develocity.sdlc-demo.gradle.com/
          DEVELOCITY_ACCESS_KEY: ${{ secrets.dv_access_key }}
        ports:
          - 8080:8080
        credentials:
          username: ${{ needs.token.outputs.oidc-user }}
          password: ${{ needs.token.outputs.oidc-token }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          server-id: artifactory
          server-username: JFROG_USER
          server-password: JFROG_PASSWORD

      - name: Build with Maven
        run: ./mvnw deploy
        env:
          JFROG_USER: ${{ needs.token.outputs.oidc-user }}
          JFROG_PASSWORD: ${{ needs.token.outputs.oidc-token }}
          CI_ID: ${{ github.run_id }}
