name: Java CI - Merge & Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
      id-token: write # This is required for the OIDC token

    env:
      MAVEN_ARGS: -V -B --no-transfer-progress

    services:
      develocity-attestations:
        image: registry.gitlab.com/cloudnative20031/opa/develocity-attestation-generator:main
        env:
          DEVELOCITY_URL: https://develocity.sdlc-demo.gradle.com/
          DEVELOCITY_ACCESS_KEY: ${{ secrets.dv_access_key }}
        ports:
          - 8080:8080
        credentials:
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

    steps:
      - uses: actions/checkout@v4

      - uses: jfrog/setup-jfrog-cli@v4
        id: jfrog
        env:
          JF_URL: https://develocitytia.jfrog.io
        with:
          oidc-provider-name: github

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          server-id: artifactory
          server-username: JFROG_USER
          server-password: JFROG_PASSWORD

      - name: Build with Maven
        run: ./mvnw deploy
        env:
          JFROG_USER: ${{ steps.jfrog.outputs.oidc-user }}
          JFROG_PASSWORD: ${{ steps.jfrog.outputs.oidc-token }}
          CI_ID: ${{ github.run_id }}
