name: Java CI - Merge & Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
      id-token: write # This is required for the OIDC token

    env:
      MAVEN_ARGS: -V -B --no-transfer-progress

    services:
      develocity:
        image: develocitytia.jfrog.io/docker-ci/develocity-attestation-generator:main
        env:
          DEVELOCITY_URL: https://develocity.sdlc-demo.gradle.com/
          DEVELOCITY_ACCESS_KEY: ${{ secrets.dv_access_key }}
        ports:
          - 8080:8080
        credentials:
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

    steps:
      - uses: actions/checkout@v4

      - uses: jfrog/setup-jfrog-cli@v4
        id: jfrog
        env:
          JF_URL: https://develocitytia.jfrog.io
        with:
          oidc-provider-name: github
          disable-job-summary: true

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          server-id: artifactory
          server-username: JFROG_USER
          server-password: JFROG_PASSWORD

      - name: Build with Maven
        run: ./mvnw deploy
        env:
          JFROG_USER: ${{ steps.jfrog.outputs.oidc-user }}
          JFROG_PASSWORD: ${{ steps.jfrog.outputs.oidc-token }}
          CI_ID: ${{ github.run_id }}-${{ github.run_attempt }}

      - name: Publish Evidence
        run: ./evidence.sh
        env:
          JFROG_CLI_SIGNING_KEY: ${{ secrets.JFROG_CLI_SIGNING_KEY }}

      - name: Trigger QA Testing Event
        run: |
          # properties from build
          source ./target/build-scan.properties
          # start async workflow
          gh workflow run qa.yaml \
            --repo 'dv-demos/qa-payment-calculator' \
            --ref 'main' \
            --raw-field image_purl="${ociImage}" \
            --raw-field image_sha256="${imageDigest}" \
            --raw-field image_repo_url="develocitytia.jfrog.io/${repo}" \
            --raw-field image_repo_name="${repo}"
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_PAT }}


      - name: Build Summary
        run: |
          source target/build-scan.properties
  
          cat << EOF > ${GITHUB_STEP_SUMMARY}
          ## Docker Image Published
          
          ---
          
          - **Image:** ${ociImage}
          - **Tag:** ${imageTag}
            
          See more details in [Build Scan](${buildScanUrl})
          
          ---
          EOF
