name: Next generation of demo

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  attest:
    name: Generate Attestations
    runs-on: ubuntu-latest
    steps:
      - uses: gradle/attest-action@c4651108a80f0220b5a4381fd8dbe9028513ca33
        with:
          attestation-publisher-url: 'https://cavendish.sdlc-demo.gradle.com'
          tenant: default
          build-scan-ids: eo5xxyg3drtoc
          subject-type: oci
          subject-name: java-payment-calculator
          subject-version: 1.0.0-SNAPSHOT-16152750186-4
          subject-digest: 1a6b2bf83435f2a9ccd33519ad3e817bf79aee6af1c7a15d26d8a256bfa9cc94
          subject-repository-url: develocitytia.jfrog.io/docker-trial